apiVersion: route53.awsctrl.io/v1alpha1
kind: HostedZone
metadata:
  name: awsctrl-io
spec:
  terminationProtection: true
  name: "awsctrl.io"
  hostedZoneConfig: 
    comment: |
      (AWS Controller created)