apiVersion: github.go.hein.dev/v1alpha1
kind: Repository
metadata:
  name: generator
  namespace: default
spec:
  organization: awsctrl
  description: "Tool used to generate all the CloudFormation controllers and types.go"
  settings:
    private: false
    issues: true
    wiki: false
    projects: true
    template: false
